Feature: Get players which are part of the specified team
  A football team has a squad of 20 players,
  as a fan, I would like to know which players played for the team in which season


  Scenario Outline: Players part of the football team
    When the football api is queried with "<team>" and "<season>"
    Then the response status code is 200
    And the response shows the "<players>" which are part of the team

    Examples: Leagues
    | team | season |  players |
    |  33  |  2020  |{"A. Tuanzebe": "https://media.api-sports.io/football/players/19182.png", "A. Wan-Bissaka": "https://media.api-sports.io/football/players/18846.png", "Alex Telles": "https://media.api-sports.io/football/players/378.png", "B. Williams": "https://media.api-sports.io/football/players/138806.png", "D. Henderson": "https://media.api-sports.io/football/players/19088.png", "David de Gea": "https://media.api-sports.io/football/players/882.png", "E. Bailly": "https://media.api-sports.io/football/players/885.png", "F. Pellistri": "https://media.api-sports.io/football/players/70078.png", "H. Maguire": "https://media.api-sports.io/football/players/2935.png", "J. Garner": "https://media.api-sports.io/football/players/895.png", "L. Grant": "https://media.api-sports.io/football/players/883.png", "L. Shaw": "https://media.api-sports.io/football/players/891.png", "N. Bishop": "https://media.api-sports.io/football/players/20319.png", "Odion Jude Ighalo": "https://media.api-sports.io/football/players/12975.png", "P. Jones": "https://media.api-sports.io/football/players/888.png", "S. Romero": "https://media.api-sports.io/football/players/884.png", "T. Fosu-Mensah": "https://media.api-sports.io/football/players/19018.png", "T. Mengi": "https://media.api-sports.io/football/players/153429.png", "V. Lindel\u00f6f": "https://media.api-sports.io/football/players/889.png", "W. Fish": "https://media.api-sports.io/football/players/153434.png"} |
    |   2  |  2020  |{ "A. Griezmann": "https://media.api-sports.io/football/players/56.png", "A. Plea": "https://media.api-sports.io/football/players/25646.png", "B. Pavard": "https://media.api-sports.io/football/players/2725.png", "C. Lenglet": "https://media.api-sports.io/football/players/133.png", "C. Tolisso": "https://media.api-sports.io/football/players/519.png", "D. Upamecano": "https://media.api-sports.io/football/players/1149.png", "F. Mendy": "https://media.api-sports.io/football/players/653.png", "J. Ikon\u00e9": "https://media.api-sports.io/football/players/22229.png", "K. Coman": "https://media.api-sports.io/football/players/508.png", "K. Mbapp\u00e9": "https://media.api-sports.io/football/players/278.png", "L. Hern\u00e1ndez": "https://media.api-sports.io/football/players/33.png", "L. Kurzawa": "https://media.api-sports.io/football/players/263.png", "M. Guendouzi": "https://media.api-sports.io/football/players/1454.png", "M. Maignan": "https://media.api-sports.io/football/players/22221.png", "M. Thuram": "https://media.api-sports.io/football/players/21509.png", "N. Fekir": "https://media.api-sports.io/football/players/668.png", "P. Kimpembe": "https://media.api-sports.io/football/players/262.png", "R. Varane": "https://media.api-sports.io/football/players/742.png", "S. Umtiti": "https://media.api-sports.io/football/players/139.png", "T. Lemar": "https://media.api-sports.io/football/players/45.png" } |
    | 100  |  2020  |{ "Alexandre Benjamin Durimel": "https://media.api-sports.io/football/players/84321.png", "Alexandre Gameiro da Conceicao": "https://media.api-sports.io/football/players/131493.png", "Arnaud Balijon": "https://media.api-sports.io/football/players/20681.png", "Charly Pereira Lage": "https://media.api-sports.io/football/players/21982.png", "Christian Gyeboaho": "https://media.api-sports.io/football/players/122117.png", "Cl\u00e9ment Goguey": "https://media.api-sports.io/football/players/126883.png", "David Pollet": "https://media.api-sports.io/football/players/8654.png", "Gregoire Pineau": "https://media.api-sports.io/football/players/87333.png", "Isma\u00ebl Camara": "https://media.api-sports.io/football/players/21074.png", "Jean-Pierre Morgan": "https://media.api-sports.io/football/players/21829.png", "Lucas Daury": "https://media.api-sports.io/football/players/24114.png", "Ludovic Gamboa": "https://media.api-sports.io/football/players/24282.png", "Malick Lopy": "https://media.api-sports.io/football/players/84080.png", "Matthieu Guerbert": "https://media.api-sports.io/football/players/24024.png", "Maxime Penneteau": "https://media.api-sports.io/football/players/128318.png", "Maxime P\u00e9lican": "https://media.api-sports.io/football/players/87364.png", "Roderic Filippi": "https://media.api-sports.io/football/players/21255.png", "Sonny Duflos": "https://media.api-sports.io/football/players/68145.png", "Thibault Cottes": "https://media.api-sports.io/football/players/84076.png" } |